import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { QRCodeCanvas } from 'qrcode.react';
import { useNavigate } from 'react-router-dom';

function Dashboard() {
  const [profile, setProfile] = useState(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();
  const email = localStorage.getItem('email');
  const profileUuid = localStorage.getItem('profileUuid');

  useEffect(() => {
    if (!email) {
      alert('Please login first!');
      navigate('/');
      return;
    }

    axios.get(`http://localhost:5000/api/profile/me/${email}`)
      .then(res => {
        setProfile(res.data);
        setLoading(false);
      })
      .catch(err => {
        console.log('Error:', err);
        alert('Error loading profile!');
        setLoading(false);
      });
  }, [email, navigate]);

  if (loading) return <h2 style={{ textAlign: 'center' }}>Loading...</h2>;
  if (!profile) return <h2 style={{ textAlign: 'center' }}>No profile found!</h2>;

  const qrData = `
🚨 EMERGENCY MEDICAL INFO 🚨
━━━━━━━━━━━━━━━━━━━━━
👤 Name: ${profile.fullName}
🩸 Blood Group: ${profile.bloodGroup}
👤 Gender: ${profile.gender}
⚠️ Allergies: ${profile.allergies?.join(', ') || 'None'}
🏥 Conditions: ${profile.conditions?.join(', ') || 'None'}
💊 Medications: ${profile.medications?.map(m => m.name).join(', ') || 'None'}
🩺 Doctor: ${profile.doctorName || 'N/A'}
📞 Doctor Phone: ${profile.doctorPhone || 'N/A'}
🫀 Organ Donor: ${profile.organDonor ? 'Yes' : 'No'}
━━━━━━━━━━━━━━━━━━━━━
Generated by MedQR App
  `.trim();

  return (
    <div style={styles.container}>
      <h1>🏥 MedQR Dashboard</h1>
      <div style={styles.card}>
        <h2>👤 {profile.fullName}</h2>
        <p>🩸 Blood Group: {profile.bloodGroup}</p>
        <p>👤 Gender: {profile.gender}</p>
        <p>⚠️ Allergies: {profile.allergies?.join(', ') || 'None'}</p>
        <p>🏥 Conditions: {profile.conditions?.join(', ') || 'None'}</p>
        <p>💊 Medications: {profile.medications?.map(m => m.name).join(', ') || 'None'}</p>
        <p>🩺 Doctor: {profile.doctorName || 'Not specified'}</p>
        <p>📞 Doctor Phone: {profile.doctorPhone || 'Not specified'}</p>
        <p>🫀 Organ Donor: {profile.organDonor ? 'Yes' : 'No'}</p>
      </div>

      <h2>📱 Your Emergency QR Code</h2>
      <p style={{ color: 'green', fontWeight: 'bold' }}>✅ Scan with any phone camera — no internet needed!</p>
      <QRCodeCanvas value={qrData} size={250} level="L" />

    
      <button onClick={() => { localStorage.clear(); window.location.href = '/'; }} style={styles.logout}>
        Logout
      </button>
    </div>
  );
}

const styles = {
  container: { maxWidth: '500px', margin: '50px auto', textAlign: 'center', fontFamily: 'Arial', padding: '20px' },
  card: { background: '#f0f8ff', padding: '20px', borderRadius: '12px', margin: '20px 0', textAlign: 'left' },
  preview: { background: '#f5f5f5', padding: '15px', borderRadius: '8px', margin: '10px 0', border: '1px solid #ddd' },
  logout: { marginTop: '20px', padding: '10px 30px', backgroundColor: '#f44336', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '16px' }
};

export default Dashboard;